### ISSUE TITLE
landing_page looks empty

### ISSUE THREAD

**Issue by willywutang** [dimagi/commcare-hq#13842]
The default landing page has username and password fields, and no styling. Do you have some guidelines on styling it?

**Comment by yuriiz** [comment]
More explanation: after setting up new instance as described at https://github.com/dimagi/commcare-hq/blob/master/README.md visiting `/` redirects to `/default_landing/` which looks like http://imgur.com/y0GfDLd
(checked no missing stylesheets on this page)
Is it a bug or configuration issue?

**Comment by czue** [comment]
This should be fixed by https://github.com/dimagi/commcare-hq/pull/13845 - it looks like that is not the right page.

The other strategy you can take is to set `settings.ENABLE_PRELOGIN_SITE` to `True` which shows the static site. we don't currently actively maintain a version of the site that does not include the prelogin page, so you may run into other issues with this set to `False`
