### ISSUE TITLE
[CEP] Deprecate CommCare Exchange

### ISSUE THREAD

**Issue by orangejenny** [dimagi/commcare-hq#25506]
**Abstract**
Remove the CommCare Exchange. This proposal is only about the technical desirability and feasibility of doing so.

**Motivation**
Reduce complexity, particularly in the domain app. The exchange is one of the areas that expects form ids to be globally unique, which results in fragile, buggy logic (see https://dimagi-dev.atlassian.net/browse/ICDS-538).

**Specification**
This would remove the following parts of CommCare:
- The `appstore` django app
- A good deal of code in the `domain` app: some views, forms, and templates
- Some attributes and logic in the `Domain` model: licensing, multimedia, copy_history, etc.
- Assorted small pieces of logic in other apps, mostly relating to the `Domain.is_snapshot` attribute: data_interfaces, messaging, reports
- 4 couch views: `snapshots`, `not_snapshots`, `published_snapshots`, `copied_from_snapshot`

**Impact on users**
Users would no longer have the ability to publish their projects or download other projects.

**Impact on hosting**
None.

**Backwards compatibility**
Projects previously downloaded from the exchange will continue to function normally.

**Release Timeline**
- Immediately: remove the ability to publish new projects to the exchange (Project Settings > CommCare Exchange)
- In 3 months: remove access to exchange (majority of the code removal described above)
- In 4 months: delete existing snapshot projects and remove remaining support code (couch views)

**Open questions and issues**
It is possible that some part of the exchange is valuable enough to be worth the related technical and support burden. This needs to be agreed upon with stakeholders before any part of this proposal is implemented. This proposal is not for discussion of this subject, but any relevant outcomes of that discussion will be recorded here.

**Comment by dannyroberts** [comment]
Thanks for putting this together @orangejenny! My main concern of course is whether customer get significant value out of it, and/or whether removing it will break a workflow—the things we always worry about when removing a feature. @djmore9 Do you have a good sense of how popular or critical a feature the exchange is?

**Comment by esoergel** [comment]
I agree that this would be great.  Honestly, the existence of the exchange hasn't been a pain point for me in a long time, though I do recall being frustrated by it a number of times in the past.  In particular, the blurred lines between "snapshots" and actual domains is a nuisance.

The rollout proposal outlined here seems appropriate, though I'm not convinced there's a need to block the ability to publish to the domain well in advance of the other work.  I don't think there's a "publish, then download" workflow there.  My guess is that most usage of the domain is people downloading from it.

Regarding the stakeholder suggestion, I know usage metrics will be a big part of the discussion.  It would be instructive to see how frequently it's used, and how many of those usages turn into real projects.  It's also important to consider the role the exchange plays, and whether we have other features which can better meet those use cases.  I'd guess that's:
* Template apps for repeated workflows
* Starting with a "Hello, world!" example rather than building an app from scratch.

The exchange is an old feature and I don't imagine has kept up-to-date with HQ's feature development.  App development is now a lot easier, and we have walk-through tools to make your first set-up go more smoothly.  Many applications rely on a number of other components of HQ, such as lookup tables, location structure, custom user data, feature flags, and others.  This means something copied from the exchange can only work in the most basic of circumstances.  Conversely, "Linked Project Spaces" is a similar feature, and it accounts for all of these auxiliary models.

**Comment by czue** [comment]
I know

> It is possible that some part of the exchange is valuable enough to be worth the related technical and support burden. This proposal is not for discussion of this subject.

But since others are weighing in, my $.02:

1. The concept of the Exchange *is* super valuable, and if implemented right could substantially increase CommCare uptake.
2. The Exchange as it exists today is not meeting that value proposition at all.
3. Therefore we should implement this change and kill the current Exchange
4. And prioritize building out a better exchange however SaaS deems necessary (which may be a long time from now)

**Comment by orangejenny** [comment]
Thanks all for the feedback (and the enthusiasm).

FYI all divisions have now signed off on the general plan from a business/product perspective. We're just figuring out timing & communication.

**Comment by orangejenny** [comment]
Closing this out, as the exchange code was removed in https://github.com/dimagi/commcare-hq/pull/25919  There's still data cleanup:
- Delete domain docs with `is_snapshot` set to true and then remove the couch views `snapshot_search`, `published_snapshots`, `copied_from_snapshot`, `snapshots`, and `not_snapshots`. @dannyroberts You're probably the person most likely to care about this, though I don't know if these couch views are large enough to be a priority for you.
- Remove exchange-related attributes from `Domain`. I doubt anyone is motivated to prioritize this.

**Comment by dannyroberts** [comment]
I went ahead and made a PR for removing the views: https://github.com/dimagi/commcare-hq/pull/26426
